version: '3.8'

services:
  # Servicio de base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: eduassist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Rasa
  rasa:
    build:
      context: ./rasa
      dockerfile: Dockerfile
    container_name: eduassist-rasa
    restart: always
    ports:
      - "${RASA_PORT}:5005"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./rasa/models:/app/models
    command: run --enable-api --cors "*"

  # Servicio de acciones de Rasa
  rasa-actions:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile
    container_name: eduassist-rasa-actions
    restart: always
    ports:
      - "${RASA_ACTIONS_PORT}:5055"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  # Servicio de la aplicación web Next.js
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduassist-web
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - rasa
      - rasa-actions
    environment:
      - NEXT_PUBLIC_RASA_API_URL=http://localhost:${RASA_PORT}
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  mysql-data:
