version: '3.8'

services:
  # Servicio de la interfaz web (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_RASA_URL=http://localhost:5005
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - rasa
    restart: unless-stopped

  # Servicio del backend (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
      - RASA_URL=http://rasa:5005
      - RASA_ACTIONS_URL=http://rasa-actions:5055
      - JWT_SECRET=${JWT_SECRET}
      - STORAGE_PATH=${STORAGE_PATH}
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - db
      - rasa
    restart: unless-stopped

  # Servicio de Rasa (Servidor principal)
  rasa:
    build: ./rasa
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
      - ./models:/app/models
    command: run --enable-api --cors "*"
    depends_on:
      - rasa-actions
    restart: unless-stopped

  # Servicio de acciones de Rasa
  rasa-actions:
    build: ./rasa
    ports:
      - "5055:5055"
    volumes:
      - ./rasa:/app
    command: run actions
    restart: unless-stopped

  # Servicio de base de datos (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  # Servicio de administración de la base de datos (Adminer)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
